GET http://localhost:3000/ HTTP/1.1


### 
GET http://localhost:3000/books HTTP/1.1

###
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
      "isbn": "112mech",
      "title":"Tentionable",
      "price": 2999,
      "author":"Ds Das",
      "category": {
         "categoryId": "mech",
         "name":"Mechanical Science"
      },
      "publisher": {
         "publisherId":"isb234civ",
         "name": "chitrangana book publisher"
      }

}

###
GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvaGl0QGdtYWlsLmNvbSIsImlhdCI6MTY1NjI1NzE1NH0.XbZiMKrGxN-GtGdJRp0vh3nN8adayZfgFasL3ukzsrQ


###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

    {
        "firstName":"Rohit",
        "lastName": "Manora",
        "userId": "0801cs",
        "password":"Raohit$#",
        "email":"rohit@gmail.com",
        "borrowBooks": []
    }

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

    {
        "email":"rohit@gmail.com",
        "password":"Rohit@1234"
    }